//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountOrder
    {
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CurrencyCode { get; set; }
        public string Description { get; set; }
        public Nullable<byte> FiscalYearLastMonth { get; set; }
        public string ForecastQuarter { get; set; }
        public string ForecastYear { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public string GeographyName_Valid { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string OpportunityName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string RecId { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionName_Valid { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string TerritoryName_Valid { get; set; }
    }
}
