//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditHistory
    {
        public string RecId { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string BusObID { get; set; }
        public string BusObName { get; set; }
        public string EventSource { get; set; }
        public string FieldName { get; set; }
        public string NewFieldValue { get; set; }
        public string OldFieldValue { get; set; }
        public string TriggerID { get; set; }
        public string TriggerName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
    }
}
