//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AverageDealSize
    {
        public string AggregateWhichRows { get; set; }
        public Nullable<decimal> AvgDealSize { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string EmployeeFullName { get; set; }
        public string RecId_ProfileEmployee { get; set; }
        public string ForecastQuarter { get; set; }
        public string ForecastYear { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public Nullable<int> Qty { get; set; }
        public string RecId { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
