//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignTask
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string Name { get; set; }
        public string DependsOn { get; set; }
        public string DependsOn_Valid { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string CampaignLink_RecID { get; set; }
        public string CampaignLink_Category { get; set; }
        public string CampaignLink_VRecID { get; set; }
        public string Subject { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> DueDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string Priority { get; set; }
        public string Priority_Valid { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string OwnerEmailAddress { get; set; }
    }
}
