//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificatePrerequisite
    {
        public string CertificateLink_RecID { get; set; }
        public string CertificateLink_Category { get; set; }
        public string CertificateLink_VRecID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string Description { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string Name { get; set; }
        public string ProductCode { get; set; }
        public string ProductLine { get; set; }
        public string ProductLink_RecID { get; set; }
        public string ProductLink_Category { get; set; }
        public string ProductLink_VRecID { get; set; }
        public string ProductName { get; set; }
        public string ProductSku { get; set; }
        public string RecId { get; set; }
        public string ReqType { get; set; }
        public string ReqType_Valid { get; set; }
    }
}
