//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitor
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string CompetitorName { get; set; }
        public string DisplayName { get; set; }
        public string Notes { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string ProfileID { get; set; }
        public string ProfileType { get; set; }
        public string Rating { get; set; }
        public string Rating_Valid { get; set; }
        public string RatingDescription { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public string Strategy { get; set; }
        public string Strengths { get; set; }
        public string Weaknesses { get; set; }
    }
}
