//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigOpportunityProductLine
    {
        public Nullable<bool> AcceptDiscountPercRevenue1 { get; set; }
        public Nullable<bool> AcceptDiscountPercRevenue2 { get; set; }
        public Nullable<bool> AcceptDiscountPercRevenue3 { get; set; }
        public Nullable<bool> AcceptDiscountPercRevenue4 { get; set; }
        public Nullable<bool> AcceptDiscountRevenue1 { get; set; }
        public Nullable<bool> AcceptDiscountRevenue2 { get; set; }
        public Nullable<bool> AcceptDiscountRevenue3 { get; set; }
        public Nullable<bool> AcceptDiscountRevenue4 { get; set; }
        public Nullable<bool> AcceptPartnerMarginRevenue1 { get; set; }
        public Nullable<bool> AcceptPartnerMarginRevenue2 { get; set; }
        public Nullable<bool> AcceptPartnerMarginRevenue3 { get; set; }
        public Nullable<bool> AcceptPartnerMarginRevenue4 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine1 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine10 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine2 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine3 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine4 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine5 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine6 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine7 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine8 { get; set; }
        public Nullable<bool> AcceptRevenue1ProdLine9 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine1 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine10 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine2 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine3 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine4 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine5 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine6 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine7 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine8 { get; set; }
        public Nullable<bool> AcceptRevenue2ProdLine9 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine1 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine10 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine2 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine3 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine4 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine5 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine6 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine7 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine8 { get; set; }
        public Nullable<bool> AcceptRevenue3ProdLine9 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine1 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine10 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine2 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine3 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine4 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine5 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine6 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine7 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine8 { get; set; }
        public Nullable<bool> AcceptRevenue4ProdLine9 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LabelRevenue1 { get; set; }
        public string LabelRevenue2 { get; set; }
        public string LabelRevenue3 { get; set; }
        public string LabelRevenue4 { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string ProdLine1 { get; set; }
        public string ProdLine1_Valid { get; set; }
        public string ProdLine10 { get; set; }
        public string ProdLine10_Valid { get; set; }
        public string ProdLine2 { get; set; }
        public string ProdLine2_Valid { get; set; }
        public string ProdLine3 { get; set; }
        public string ProdLine3_Valid { get; set; }
        public string ProdLine4 { get; set; }
        public string ProdLine4_Valid { get; set; }
        public string ProdLine5 { get; set; }
        public string ProdLine5_Valid { get; set; }
        public string ProdLine6 { get; set; }
        public string ProdLine6_Valid { get; set; }
        public string ProdLine7 { get; set; }
        public string ProdLine7_Valid { get; set; }
        public string ProdLine8 { get; set; }
        public string ProdLine8_Valid { get; set; }
        public string ProdLine9 { get; set; }
        public string ProdLine9_Valid { get; set; }
        public Nullable<byte> ProdLineCount { get; set; }
        public string ProdLineLabel { get; set; }
        public string RecId { get; set; }
        public string Revenue1Type { get; set; }
        public string Revenue1Type_Valid { get; set; }
        public string Revenue2Type { get; set; }
        public string Revenue2Type_Valid { get; set; }
        public string Revenue3Type { get; set; }
        public string Revenue3Type_Valid { get; set; }
        public string Revenue4Type { get; set; }
        public string Revenue4Type_Valid { get; set; }
        public Nullable<bool> ShowRevenue1 { get; set; }
        public Nullable<bool> ShowRevenue2 { get; set; }
        public Nullable<bool> ShowRevenue3 { get; set; }
        public Nullable<bool> ShowRevenue4 { get; set; }
    }
}
