//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTab
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string ACH { get; set; }
        public Nullable<System.DateTime> ACHexpiration { get; set; }
        public string ACHOrigination { get; set; }
        public Nullable<System.DateTime> ACHOrigination_expiration { get; set; }
        public string ALM { get; set; }
        public Nullable<System.DateTime> ALMexpiration { get; set; }
        public string BillPay { get; set; }
        public Nullable<System.DateTime> BillPay_Expiration { get; set; }
        public string BranchCaptureOption { get; set; }
        public Nullable<System.DateTime> BranchCaptureOption_Expiration { get; set; }
        public string BSA { get; set; }
        public Nullable<System.DateTime> BSAexpiration { get; set; }
        public string BSAAudit { get; set; }
        public Nullable<System.DateTime> BSAAudit_Expiration { get; set; }
        public string CallReport { get; set; }
        public Nullable<System.DateTime> CallReport_Expiration { get; set; }
        public string CallReportInterface { get; set; }
        public Nullable<System.DateTime> CallReportInterface_Expiration { get; set; }
        public string CardSentry { get; set; }
        public Nullable<System.DateTime> CardSentry_Expiration { get; set; }
        public string CardSentryPinnedPOS { get; set; }
        public Nullable<System.DateTime> CardSentryPinnedPOS_Expiration { get; set; }
        public string CardSentryRTD { get; set; }
        public Nullable<System.DateTime> CardSentryRTD_Expiration { get; set; }
        public string CheckImageSystem { get; set; }
        public Nullable<System.DateTime> CheckImageSystem_Expiration { get; set; }
        public string CheckRecovery { get; set; }
        public Nullable<System.DateTime> CheckRecovery_expiration { get; set; }
        public string CheckWriter { get; set; }
        public Nullable<System.DateTime> CheckWriter_Expiration { get; set; }
        public string CIP { get; set; }
        public Nullable<System.DateTime> CIP_Expiration { get; set; }
        public string CommLines { get; set; }
        public Nullable<System.DateTime> CommLines_Expiration { get; set; }
        public string DebitCards { get; set; }
        public Nullable<System.DateTime> DebitCard_Expiration { get; set; }
        public string DebitCardRealtime { get; set; }
        public Nullable<System.DateTime> DebitCardRealTime_Expiration { get; set; }
        public string InstantIssueCards { get; set; }
        public Nullable<System.DateTime> InstantIssueCards_Expiration { get; set; }
        public string Deposit { get; set; }
        public Nullable<System.DateTime> Deposit_Expiration { get; set; }
        public string DocLinksCrTracking { get; set; }
        public Nullable<System.DateTime> DocLinksCrTracking_Expiration { get; set; }
        public string DocumentStorage { get; set; }
        public Nullable<System.DateTime> DocumentStorageExpiration { get; set; }
        public string EmailStatements { get; set; }
        public Nullable<System.DateTime> EmailStatements_Expiration { get; set; }
        public string ENotices { get; set; }
        public Nullable<System.DateTime> ENotices_Expiration { get; set; }
        public string eSafeBranding { get; set; }
        public Nullable<System.DateTime> eSafeBranding_Expiration { get; set; }
        public string FinCEN { get; set; }
        public Nullable<System.DateTime> FinCEN_Expiration { get; set; }
        public string HotSite { get; set; }
        public Nullable<System.DateTime> HotSite_Expiration { get; set; }
        public string Internet { get; set; }
        public Nullable<System.DateTime> Internet_Expiration { get; set; }
        public string InternetCashMgmt { get; set; }
        public Nullable<System.DateTime> InternetCashMgt_Expiration { get; set; }
        public string InternetDesign { get; set; }
        public Nullable<System.DateTime> InternetDesign_Expiration { get; set; }
        public string InternetMarketing { get; set; }
        public Nullable<System.DateTime> InternetMarketing_Expiration { get; set; }
        public string InternetMobileApp { get; set; }
        public Nullable<System.DateTime> InternetMobileApp_Expiration { get; set; }
        public string InternetPFM { get; set; }
        public Nullable<System.DateTime> InternetPFM_Expiration { get; set; }
        public string InternetPositivePay { get; set; }
        public Nullable<System.DateTime> InternetPositivePay_Experation { get; set; }
        public string InternetProvider { get; set; }
        public Nullable<System.DateTime> InternetProvider_Expiration { get; set; }
        public string InternetRealTime { get; set; }
        public Nullable<System.DateTime> InternetRealTime_Expiration { get; set; }
        public string Intranet { get; set; }
        public Nullable<System.DateTime> Intranet_Expiration { get; set; }
        public string LoanPricing { get; set; }
        public Nullable<System.DateTime> LoanPricing_Expiration { get; set; }
        public string LoanPlatform { get; set; }
        public Nullable<System.DateTime> LoanPlatform_Expiration { get; set; }
        public string LoansPlus { get; set; }
        public Nullable<System.DateTime> LoansPlus_Expiration { get; set; }
        public string MerchantCapture { get; set; }
        public Nullable<System.DateTime> MerchantCapture_Expiration { get; set; }
        public string MerchantServices { get; set; }
        public Nullable<System.DateTime> MerchantServices_Expiration { get; set; }
        public string MoneyLinksAlerts { get; set; }
        public Nullable<System.DateTime> MoneyLinksAlerts_Expiration { get; set; }
        public string MSIStatements { get; set; }
        public Nullable<System.DateTime> MSIStatements_Expiration { get; set; }
        public string NetworkAudit { get; set; }
        public Nullable<System.DateTime> NetworkAudit_Expiration { get; set; }
        public string NetworkBackup { get; set; }
        public Nullable<System.DateTime> NetworkBackup_Expiration { get; set; }
        public string NetworkManagement { get; set; }
        public Nullable<System.DateTime> NetworkManagement_Expiration { get; set; }
        public string OFAC { get; set; }
        public Nullable<System.DateTime> OFAC_Expiration { get; set; }
        public string PCEncryption { get; set; }
        public Nullable<System.DateTime> PCEncryption_Expiration { get; set; }
        public string Profitability { get; set; }
        public Nullable<System.DateTime> Profitability_Expiration { get; set; }
        public string RegCC { get; set; }
        public Nullable<System.DateTime> RegCC_Expiration { get; set; }
        public string RewardsChecking { get; set; }
        public Nullable<System.DateTime> RewardsChecking_Expiration { get; set; }
        public string SecureEmail { get; set; }
        public Nullable<System.DateTime> SecureEmail_Expiration { get; set; }
        public string SecurityAudit { get; set; }
        public Nullable<System.DateTime> SecurityAudit_Expiration { get; set; }
        public string StatementPrinting { get; set; }
        public Nullable<System.DateTime> StatementPrinting_Expiration { get; set; }
        public string Supplies { get; set; }
        public Nullable<System.DateTime> Supplies_Expiration { get; set; }
        public string Teller { get; set; }
        public Nullable<System.DateTime> Teller_Expiration { get; set; }
        public string Training { get; set; }
        public Nullable<System.DateTime> Training_Expiration { get; set; }
        public string UnixBackup { get; set; }
        public Nullable<System.DateTime> UnixBackup_Expiration { get; set; }
        public string VendorManagement { get; set; }
        public Nullable<System.DateTime> VendorManagement_Expiration { get; set; }
        public string Voice { get; set; }
        public Nullable<System.DateTime> Voice_Expiration { get; set; }
        public string WebsiteAudit { get; set; }
        public Nullable<System.DateTime> WebsiteAudit_Expiration { get; set; }
        public string Wire { get; set; }
        public Nullable<System.DateTime> Wire_Expiration { get; set; }
        public string DisasterRecovery { get; set; }
        public Nullable<System.DateTime> DisasterRecoveryExpiration { get; set; }
    }
}
