//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string AccountLink_RecID { get; set; }
        public string AccountLink_Category { get; set; }
        public string AccountLink_VRecID { get; set; }
        public string AccountName { get; set; }
        public string AssistancePhoneExt { get; set; }
        public string Assistant { get; set; }
        public string AssistantPhone { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<bool> BirthdayNextMonth { get; set; }
        public string ContactID { get; set; }
        public string ContactSupervisorName { get; set; }
        public string ContactType { get; set; }
        public string ContactType_Valid { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string Department { get; set; }
        public string Department_Valid { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public string GeographyName_Valid { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastName { get; set; }
        public string LoginUserLink_RecID { get; set; }
        public string LoginUserLink_Category { get; set; }
        public string LoginUserLink_VRecID { get; set; }
        public string MiddleName { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string Phone1Link_RecID { get; set; }
        public string Phone1Link_Category { get; set; }
        public string Phone1Link_VRecID { get; set; }
        public string Phone2Link_RecID { get; set; }
        public string Phone2Link_Category { get; set; }
        public string Phone2Link_VRecID { get; set; }
        public string Phone3Link_RecID { get; set; }
        public string Phone3Link_Category { get; set; }
        public string Phone3Link_VRecID { get; set; }
        public string Phone4Link_RecID { get; set; }
        public string Phone4Link_Category { get; set; }
        public string Phone4Link_VRecID { get; set; }
        public string PreferredMethodContact { get; set; }
        public string PreferredMethodConta_Valid { get; set; }
        public string Prefix { get; set; }
        public string Prefix_Valid { get; set; }
        public string PrimaryAddressLink_RecID { get; set; }
        public string PrimaryAddressLink_Category { get; set; }
        public string PrimaryAddressLink_VRecID { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryEmailLink_RecID { get; set; }
        public string PrimaryEmailLink_Category { get; set; }
        public string PrimaryEmailLink_VRecID { get; set; }
        public string PrimaryWebLink_RecID { get; set; }
        public string PrimaryWebLink_Category { get; set; }
        public string PrimaryWebLink_VRecID { get; set; }
        public string RecId { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionName_Valid { get; set; }
        public string Source { get; set; }
        public string Source_Valid { get; set; }
        public string Spouse { get; set; }
        public string Suffix { get; set; }
        public string Suffix_Valid { get; set; }
        public string SupervisorLink_RecID { get; set; }
        public string SupervisorLink_Category { get; set; }
        public string SupervisorLink_VRecID { get; set; }
        public string Territory { get; set; }
        public string Territory_Valid { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string TerritoryName_Valid { get; set; }
        public string Title { get; set; }
        public string Title_Valid { get; set; }
        public string McM_Contact_ID { get; set; }
        public string McM_Bank_ID { get; set; }
        public string McM_Location_ID { get; set; }
        public string McM_Location_ID_Valid { get; set; }
        public Nullable<bool> McM_alerts { get; set; }
        public Nullable<bool> McM_president { get; set; }
        public Nullable<bool> McM_cashier { get; set; }
        public Nullable<bool> McM_computer_room { get; set; }
        public Nullable<bool> McM_ceo { get; set; }
        public Nullable<bool> McM_coo { get; set; }
        public Nullable<bool> McM_deposit_ops_head { get; set; }
        public Nullable<bool> McM_lending_ops_head { get; set; }
        public Nullable<bool> McM_cio { get; set; }
        public Nullable<bool> McM_compliance_officer { get; set; }
        public Nullable<bool> McM_bsa_officer { get; set; }
        public Nullable<bool> McM_it_manager { get; set; }
        public Nullable<bool> McM_training { get; set; }
        public string McM_Location_Name { get; set; }
        public string McM_Location_Name_Valid { get; set; }
        public string McM_Data_Center { get; set; }
        public Nullable<bool> McM_Anonymous_Flag { get; set; }
        public string AccountCity { get; set; }
        public string McM_survey_number { get; set; }
        public string McM_survey_number_Valid { get; set; }
        public Nullable<bool> McM_survey_logical { get; set; }
        public Nullable<bool> McM_president_logical { get; set; }
        public Nullable<bool> McM_cashier_logical { get; set; }
        public Nullable<bool> McM_ceo_logical { get; set; }
        public Nullable<bool> McM_Correspondent1_Logical { get; set; }
        public Nullable<bool> McM_Correspondent2_Logical { get; set; }
        public Nullable<bool> McM_executive_logical { get; set; }
        public Nullable<bool> McM_Operations_Logical { get; set; }
        public Nullable<bool> McM_Disaster_Logical { get; set; }
        public Nullable<bool> McM_Contact_Security_Logical { get; set; }
        public Nullable<bool> McM_Contact_Security { get; set; }
        public Nullable<bool> ContactSurveySent { get; set; }
        public string McM_DR_Phone { get; set; }
    }
}
