//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyCode
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string Code { get; set; }
        public string IssuingCountry { get; set; }
        public string IssuingCountry_Valid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> SmallestDenomination { get; set; }
        public string GroupingSymbol { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencySymbol_Valid { get; set; }
        public string DecimalSymbol { get; set; }
        public Nullable<bool> UseLocaleConvention { get; set; }
        public string CurrencySymbolPosition { get; set; }
        public string CurrencySymbolPositi_Valid { get; set; }
    }
}
