//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeForecastEmp
    {
        public string ForecastYear { get; set; }
        public string ForecastMonth { get; set; }
        public string ForecastQuarter { get; set; }
        public string EmployeeFullName { get; set; }
        public string RecId_ProfileEmployee { get; set; }
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy1 { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string AggregateWhichRows { get; set; }
        public Nullable<decimal> m_BestCase__TCV { get; set; }
        public Nullable<decimal> m_Closed__TCV { get; set; }
        public Nullable<decimal> m_Committed__TCV { get; set; }
        public Nullable<decimal> m_Likely__TCV { get; set; }
        public Nullable<decimal> m_Weighted__TCV { get; set; }
        public Nullable<decimal> m_BestCase__PCV { get; set; }
        public Nullable<decimal> m_Closed__PCV { get; set; }
        public Nullable<decimal> m_Committed__PCV { get; set; }
        public Nullable<decimal> m_Weighted__PCV { get; set; }
        public Nullable<decimal> m_Likely__PCV { get; set; }
        public Nullable<decimal> m_Amount__TCV { get; set; }
        public string Territory { get; set; }
        public string CURRENCYCODE { get; set; }
    }
}
