//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecast
    {
        public Nullable<int> BookedDeals { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CURRENCYCODE { get; set; }
        public string CURRENCYCODE_Valid { get; set; }
        public Nullable<int> DealsInPlay { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeLink_RecID { get; set; }
        public string EmployeeLink_Category { get; set; }
        public string EmployeeLink_VRecID { get; set; }
        public string ForecastMonth { get; set; }
        public string ForecastMonth_Valid { get; set; }
        public Nullable<byte> ForecastMonthNo { get; set; }
        public string ForecastQuarter { get; set; }
        public string ForecastQuarter_Valid { get; set; }
        public string ForecastYear { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public Nullable<decimal> m_BestCase__PCV { get; set; }
        public Nullable<decimal> m_BestCase__TCV { get; set; }
        public Nullable<decimal> m_Closed__PCV { get; set; }
        public Nullable<decimal> m_Closed__TCV { get; set; }
        public Nullable<decimal> m_Committed__PCV { get; set; }
        public Nullable<decimal> m_Committed__TCV { get; set; }
        public Nullable<decimal> m_Likely__PCV { get; set; }
        public Nullable<decimal> m_Likely__TCV { get; set; }
        public Nullable<decimal> m_Weighted__PCV { get; set; }
        public Nullable<decimal> m_Weighted__TCV { get; set; }
        public string Owner { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string ProductInterest { get; set; }
        public string RecId { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> SlippedDeals { get; set; }
        public string Territory { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
    }
}
