//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastAdjustment
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string AdjustmentYear { get; set; }
        public string AdjustmentQuarter { get; set; }
        public string AdjustmentMonth { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string EffectiveDate_Valid { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string CURRENCYCODE { get; set; }
        public string CURRENCYCODE_Valid { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public Nullable<decimal> m_Adjustment__TCV { get; set; }
        public Nullable<decimal> m_Adjustment__PCV { get; set; }
        public string EmployeeLink_RecID { get; set; }
        public string EmployeeLink_Category { get; set; }
        public string EmployeeLink_VRecID { get; set; }
        public string Territory { get; set; }
        public string Territory_Valid { get; set; }
        public Nullable<short> FiscalYearLastMonth { get; set; }
    }
}
