//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusionDefDelete
    {
        public string FDRecID { get; set; }
        public string FDObType { get; set; }
        public string DefRecID { get; set; }
        public string FDName { get; set; }
        public string Perspective { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
    }
}
