//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusionDictionary
    {
        public string CultureName { get; set; }
        public string Perspective { get; set; }
        public string DictID { get; set; }
        public string GenericValue { get; set; }
        public string CultureValue { get; set; }
        public Nullable<int> RowsOrder { get; set; }
    }
}
