//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusionCounter
    {
        public string RecID { get; set; }
        public string Name { get; set; }
        public string CounterValue { get; set; }
        public Nullable<System.DateTime> LastResetDateTime { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
    }
}
