//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusionBusProc
    {
        public string FDRecID { get; set; }
        public string FDObType { get; set; }
        public string FDCategory { get; set; }
        public string FDName { get; set; }
        public string FDAlias { get; set; }
        public string FDDesc { get; set; }
        public string FDFolder { get; set; }
        public int FDVersion { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string CultureName { get; set; }
        public string DefRecID { get; set; }
        public string Scope { get; set; }
        public string ScopeOwner { get; set; }
        public string Perspective { get; set; }
        public string LinkedTo { get; set; }
        public string Flags { get; set; }
        public string FDDetails { get; set; }
    }
}
