//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusionLink
    {
        public string RecID { get; set; }
        public string SourceID { get; set; }
        public string SourceLoc { get; set; }
        public string SourceName { get; set; }
        public string SourceBase { get; set; }
        public string TargetID { get; set; }
        public string TargetLoc { get; set; }
        public string TargetName { get; set; }
        public string TargetBase { get; set; }
        public string RelationshipName { get; set; }
    }
}
