//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusionSessionTracker
    {
        public string SessionID { get; set; }
        public string LoginID { get; set; }
        public string AuthID { get; set; }
        public string AuthSource { get; set; }
        public string UserStatusID { get; set; }
        public string LicenseList { get; set; }
        public string SecurityGroupID { get; set; }
        public string BusObDefID { get; set; }
        public string BusObDefName { get; set; }
        public string UserBusObID { get; set; }
        public string BusUnitDefID { get; set; }
        public string UserBusUnit { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public System.DateTime LastAccessDateTime { get; set; }
    }
}
