//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusionSetting
    {
        public string RecID { get; set; }
        public string ModuleName { get; set; }
        public string Category { get; set; }
        public string Scope { get; set; }
        public string ScopeOwner { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string Details { get; set; }
    }
}
