//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusionUser
    {
        public string RecID { get; set; }
        public string UserType { get; set; }
        public string LoginID { get; set; }
        public string Pwd { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> PasswordChangedDateTime { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
    }
}
