//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GA_DepartmentReports
    {
        public long DepartmentReportsID { get; set; }
        public string Procedure { get; set; }
        public string Department { get; set; }
        public string Parameters { get; set; }
        public string Email { get; set; }
        public Nullable<int> Enabled { get; set; }
    }
}
