//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GA_Settings
    {
        public long SettingsID { get; set; }
        public Nullable<System.DateTime> LastAlertsSent { get; set; }
        public Nullable<short> AlertSendInterval { get; set; }
        public Nullable<System.DateTime> LastAlertSync { get; set; }
        public Nullable<short> AlertSyncInterval { get; set; }
        public System.DateTime LastGetAlertCounts { get; set; }
        public Nullable<System.DateTime> GetAlertCountsTime { get; set; }
        public Nullable<System.DateTime> LastGetStDev { get; set; }
        public Nullable<System.DateTime> GetStDevTime { get; set; }
        public Nullable<bool> IsUpdating { get; set; }
        public long OpenCasesDays { get; set; }
        public System.DateTime OpenCasesTime { get; set; }
        public System.DateTime LastOpenCases { get; set; }
        public string OpenCasesEmail { get; set; }
        public Nullable<System.DateTime> DailyStatusTime { get; set; }
        public Nullable<System.DateTime> LastDailyStatus { get; set; }
        public string DailyStatusEmail { get; set; }
        public Nullable<System.DateTime> DeptReportsTime { get; set; }
        public Nullable<System.DateTime> LastDeptReports { get; set; }
        public Nullable<System.DateTime> DeptCaseReportsTime { get; set; }
        public Nullable<System.DateTime> LastDeptCaseReports { get; set; }
    }
}
