//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string Issue1 { get; set; }
        public string Notes { get; set; }
        public string Priority { get; set; }
        public string Priority_Valid { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public string IssueOwner { get; set; }
        public string IssueOwner_Valid { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string McM_Issue { get; set; }
        public string McM_Resolution { get; set; }
    }
}
