//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadRoutingConfiguration
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string RoutingMode { get; set; }
        public string RoutingMode_Valid { get; set; }
        public string FollowupActivity { get; set; }
        public string FollowupActivity_Valid { get; set; }
        public Nullable<int> FollowupWaitTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ProcessUnattendedLeads { get; set; }
    }
}
