//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadStatusforEmployee
    {
        public string AggregateWhichRows { get; set; }
        public Nullable<int> ConvertedStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string EmployeeFullName { get; set; }
        public string RecId_ProfileEmployee { get; set; }
        public string ForecastMonth { get; set; }
        public string ForecastQuarter { get; set; }
        public string ForecastWeek { get; set; }
        public string ForecastYear { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public Nullable<int> NewStatus { get; set; }
        public Nullable<int> NotTouchedStatus { get; set; }
        public Nullable<int> QualifiedStatus { get; set; }
        public string RecId { get; set; }
        public Nullable<int> RejectedStatus { get; set; }
    }
}
