//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public string AccountName { get; set; }
        public Nullable<System.DateTime> AssignedDateTime { get; set; }
        public Nullable<decimal> BudgetPCV { get; set; }
        public Nullable<byte> BudgetScore { get; set; }
        public Nullable<decimal> BudgetTCV { get; set; }
        public string CampaignLink_RecID { get; set; }
        public string CampaignLink_Category { get; set; }
        public string CampaignSource { get; set; }
        public string Category { get; set; }
        public string Category_Valid { get; set; }
        public Nullable<byte> CategoryScore { get; set; }
        public string CompanyName { get; set; }
        public string CompanySize { get; set; }
        public string CompanySize_Valid { get; set; }
        public Nullable<byte> CompanySizeScore { get; set; }
        public string ContactFullName { get; set; }
        public string ConvertedAccountLink_RecID { get; set; }
        public string ConvertedAccountLink_Category { get; set; }
        public string ConvertedContactLink_RecID { get; set; }
        public string ConvertedContactLink_Category { get; set; }
        public string ConvertedOpportunity_RecID { get; set; }
        public string ConvertedOpportunity_Category { get; set; }
        public Nullable<int> ConvertedStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string DisplayName { get; set; }
        public string EmployeeFullName { get; set; }
        public string FirstName { get; set; }
        public Nullable<byte> FiscalYearLastMonth { get; set; }
        public string ForecastMonth { get; set; }
        public string ForecastQuarter { get; set; }
        public string ForecastWeek { get; set; }
        public string ForecastYear { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public string GeographyName_Valid { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public string Industry { get; set; }
        public string Industry_Valid { get; set; }
        public string KeyCode { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastName { get; set; }
        public string LeadCategory { get; set; }
        public Nullable<System.DateTime> LeadFollowupDateTime { get; set; }
        public string LeadSource { get; set; }
        public string LeadSource_Valid { get; set; }
        public string MiddleName { get; set; }
        public string NAICSCode { get; set; }
        public Nullable<int> NewStatus { get; set; }
        public Nullable<int> NotTouchedStatus { get; set; }
        public Nullable<short> NumberOfSeats { get; set; }
        public string OpportunityName { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string Partner { get; set; }
        public string PartnerEmailAddress { get; set; }
        public string PartnerLink_RecID { get; set; }
        public string PartnerLink_Category { get; set; }
        public string PartnerLink_VRecID { get; set; }
        public string Phone1Link_RecID { get; set; }
        public string Phone1Link_Category { get; set; }
        public string Phone2Link_RecID { get; set; }
        public string Phone2Link_Category { get; set; }
        public string Phone3Link_RecID { get; set; }
        public string Phone3Link_Category { get; set; }
        public string Phone4Link_RecID { get; set; }
        public string Phone4Link_Category { get; set; }
        public string Prefix { get; set; }
        public string Prefix_Valid { get; set; }
        public string PrimaryAddressLink_RecID { get; set; }
        public string PrimaryAddressLink_Category { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryEmailLink_RecID { get; set; }
        public string PrimaryEmailLink_Category { get; set; }
        public string PrimaryWebAddressLink_RecID { get; set; }
        public string PrimaryWebAddressLink_Category { get; set; }
        public string ProductInterest { get; set; }
        public string ProductInterest_Valid { get; set; }
        public Nullable<byte> ProductInterestScore { get; set; }
        public Nullable<int> QualifiedStatus { get; set; }
        public string Rating { get; set; }
        public string RecId { get; set; }
        public string Region { get; set; }
        public string Region_Valid { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionName_Valid { get; set; }
        public Nullable<int> RejectedStatus { get; set; }
        public Nullable<short> Score { get; set; }
        public string SearchStatus { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public Nullable<System.DateTime> StatusModifiedDateTime { get; set; }
        public string Suffix { get; set; }
        public string Suffix_Valid { get; set; }
        public string Territory { get; set; }
        public string Territory_Valid { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string TerritoryName_Valid { get; set; }
        public Nullable<byte> TimesRejected { get; set; }
        public string TimeToPurchase { get; set; }
        public string TimeToPurchase_Valid { get; set; }
        public Nullable<short> TimeToPurchaseScore { get; set; }
        public string Title { get; set; }
        public string Title_Valid { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string TransactionCurrencyC_Valid { get; set; }
        public Nullable<short> TriggerRecalc { get; set; }
    }
}
