//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadQualQuestion
    {
        public string AnswerLink_RecID { get; set; }
        public string AnswerLink_Category { get; set; }
        public string AnswerLink_VRecID { get; set; }
        public string AnswerText { get; set; }
        public string AnswerText_Valid { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string ProductInterest { get; set; }
        public string ProductInterest_Valid { get; set; }
        public string QuestionLink_RecID { get; set; }
        public string QuestionLink_Category { get; set; }
        public string QuestionLink_VRecID { get; set; }
        public string QuestionText { get; set; }
        public string QuestionText_Valid { get; set; }
        public string RecId { get; set; }
    }
}
