//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingListMember
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string Prefix { get; set; }
        public string Prefix_Valid { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Suffix_Valid { get; set; }
        public string AccountName { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Phone4 { get; set; }
        public string Email1 { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Zip { get; set; }
        public string Country { get; set; }
        public Nullable<bool> DoNotContact { get; set; }
        public string Industry { get; set; }
        public string Industry_Valid { get; set; }
        public string NAICSCode { get; set; }
        public string NAICSCode_Valid { get; set; }
        public string Title { get; set; }
        public string Title_Valid { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string TransactionCurrencyC_Valid { get; set; }
        public Nullable<decimal> BudgetPCV { get; set; }
        public Nullable<decimal> BudgetTCV { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string TimeToPurchase { get; set; }
        public string TimeToPurchase_Valid { get; set; }
        public Nullable<int> NumberOfTimesContacted { get; set; }
        public string FullName { get; set; }
    }
}
