//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class McM_AuditHistory
    {
        public long AuditHistID { get; set; }
        public Nullable<decimal> CaseNumber { get; set; }
        public string CSINumber { get; set; }
        public string BankContact { get; set; }
        public string BankName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public string Product { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public string Owner { get; set; }
        public string OwnerTeam { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Resolution { get; set; }
    }
}
