//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class McMBankVisitReport
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string OwnerType { get; set; }
        public string Owner { get; set; }
        public string OwnerTeam { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public Nullable<System.DateTime> McMVisitDate { get; set; }
        public Nullable<byte> McMVisitRating { get; set; }
        public string McMVisitedBy { get; set; }
        public string McMMetWith { get; set; }
        public string McMSynopsis { get; set; }
        public string McMHotTopics { get; set; }
        public string McMPositiveFeedback { get; set; }
        public string McMProductsDiscussed { get; set; }
        public string McMProductsProposed { get; set; }
        public string McMProductsSold { get; set; }
        public string McMBankName { get; set; }
    }
}
