//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offering
    {
        public string BriefDescription { get; set; }
        public Nullable<bool> Bundle { get; set; }
        public string CaseLink_RecID { get; set; }
        public string CaseLink_Category { get; set; }
        public string CaseLink_VRecID { get; set; }
        public string Category { get; set; }
        public string CategoryLink_RecID { get; set; }
        public string CategoryLink_Category { get; set; }
        public string CategoryLink_VRecID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CURRENCYCODE { get; set; }
        public string CURRENCYCODE_Valid { get; set; }
        public string Description { get; set; }
        public string Frequency { get; set; }
        public string Frequency_Valid { get; set; }
        public Nullable<decimal> GrossMargin { get; set; }
        public string InternalDescription { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LeadLink_RecID { get; set; }
        public string LeadLink_Category { get; set; }
        public string LeadLink_VRecID { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public string Manufacturer { get; set; }
        public string ManufacturerLink_RecID { get; set; }
        public string ManufacturerLink_Category { get; set; }
        public string ManufacturerLink_VRecID { get; set; }
        public string ManufacturerPartNo { get; set; }
        public Nullable<decimal> m_Cost__PCV { get; set; }
        public Nullable<decimal> m_Cost__TCV { get; set; }
        public Nullable<decimal> m_FixedPrice__PCV { get; set; }
        public Nullable<decimal> m_FixedPrice__TCV { get; set; }
        public Nullable<decimal> m_ListPrice__PCV { get; set; }
        public Nullable<decimal> m_ListPrice__TCV { get; set; }
        public Nullable<decimal> m_MSRP__PCV { get; set; }
        public Nullable<decimal> m_MSRP__TCV { get; set; }
        public Nullable<decimal> m_PricingValue__PCV { get; set; }
        public Nullable<decimal> m_PricingValue__TCV { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public string OfferingType { get; set; }
        public Nullable<bool> Orderable { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string PLLink_RecID { get; set; }
        public string PLLink_Category { get; set; }
        public string PLLink_VRecID { get; set; }
        public string Pricing { get; set; }
        public string Pricing_Valid { get; set; }
        public string PricingLink_RecID { get; set; }
        public string PricingLink_Category { get; set; }
        public string PricingLink_VRecID { get; set; }
        public string PricingText { get; set; }
        public Nullable<decimal> PricingValue { get; set; }
        public Nullable<decimal> PricingValuePct { get; set; }
        public string PricingValuePct_Valid { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductLine { get; set; }
        public string ProductLineLink_RecID { get; set; }
        public string ProductLineLink_Category { get; set; }
        public string ProductLineLink_VRecID { get; set; }
        public string ProductName { get; set; }
        public string ProductSku { get; set; }
        public string ProductType { get; set; }
        public string ProductType_Valid { get; set; }
        public string ProductVendorName { get; set; }
        public string ProductVersionNo { get; set; }
        public string RecId { get; set; }
        public Nullable<bool> Recurring { get; set; }
        public string RevenueType { get; set; }
        public string RevenueType_Valid { get; set; }
        public string ServiceDuration { get; set; }
        public string ServiceDuration_Valid { get; set; }
        public Nullable<bool> ShowFixedPrice { get; set; }
        public Nullable<bool> ShowListPrice { get; set; }
        public Nullable<bool> ShowPricingAmt { get; set; }
        public Nullable<bool> ShowPricingPct { get; set; }
        public Nullable<bool> ShowPricingValue { get; set; }
        public Nullable<bool> ShowServiceDuration { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public string TypeOfCurrency { get; set; }
        public string TypeOfCurrency_Valid { get; set; }
        public Nullable<bool> UpdateTerritoryPricing { get; set; }
        public Nullable<bool> ValidateVolPricing { get; set; }
        public string VendorLink_RecID { get; set; }
        public string VendorLink_Category { get; set; }
        public string VendorLink_VRecID { get; set; }
        public string VLink_RecID { get; set; }
        public string VLink_Category { get; set; }
        public string VLink_VRecID { get; set; }
    }
}
