//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpportunityTemplate
    {
        public string AccountLink_RecID { get; set; }
        public string AccountLink_Category { get; set; }
        public string AccountLink_VRecID { get; set; }
        public string AccountName { get; set; }
        public string AssignedTeam { get; set; }
        public string Campaign { get; set; }
        public string CampaignLink_RecID { get; set; }
        public string CampaignLink_Category { get; set; }
        public string CampaignLink_VRecID { get; set; }
        public Nullable<short> Certainty { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Code { get; set; }
        public string CompanyName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactLink_RecID { get; set; }
        public string ContactLink_Category { get; set; }
        public string ContactLink_VRecID { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CustomerReference { get; set; }
        public Nullable<int> DaysElapsed { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> Difference { get; set; }
        public string DisplayName { get; set; }
        public string EmployeeLink_RecID { get; set; }
        public string EmployeeLink_Category { get; set; }
        public string EmployeeLink_VRecID { get; set; }
        public Nullable<decimal> EstimatedBudget { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public string GeographyName_Valid { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LeadLink_RecID { get; set; }
        public string LeadLink_Category { get; set; }
        public string LeadLink_VRecID { get; set; }
        public string LeadName { get; set; }
        public Nullable<decimal> mEstimatedBudgetPCV { get; set; }
        public Nullable<decimal> mEstimatedBudgetTCV { get; set; }
        public string Methodology { get; set; }
        public string Methodology_Valid { get; set; }
        public Nullable<decimal> mManualForecastPCV { get; set; }
        public Nullable<decimal> mManualForecastTCV { get; set; }
        public Nullable<decimal> mRecurrRevenueMonthlyPCV { get; set; }
        public Nullable<decimal> mRecurrRevenueMonthlyTCV { get; set; }
        public Nullable<decimal> mRecurrRevenueQuarterlyPCV { get; set; }
        public Nullable<decimal> mRecurrRevenueQuarterlyTCV { get; set; }
        public Nullable<decimal> mRecurrRevenueYearlyPCV { get; set; }
        public Nullable<decimal> mRecurrRevenueYearlyTCV { get; set; }
        public Nullable<decimal> mRevenuePCV { get; set; }
        public Nullable<decimal> mRevenueTCV { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string Pain { get; set; }
        public string Partner { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string Priority { get; set; }
        public string Priority_Valid { get; set; }
        public Nullable<short> Probability { get; set; }
        public string RecId { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionName_Valid { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public string Source { get; set; }
        public string Source_Valid { get; set; }
        public string SourceType { get; set; }
        public string Stage { get; set; }
        public string Stage_Valid { get; set; }
        public string StageLink_RecID { get; set; }
        public string StageLink_Category { get; set; }
        public string StageLink_VRecID { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public string StatusLink_RecID { get; set; }
        public string StatusLink_Category { get; set; }
        public string StatusLink_VRecID { get; set; }
        public Nullable<System.DateTime> TargetCloseDate { get; set; }
        public string TargetCloseDate_Valid { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string Territory { get; set; }
        public string Territory_Valid { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string TerritoryName_Valid { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string TransactionCurrencyC_Valid { get; set; }
    }
}
