//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerMargin
    {
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public string PartnerLink_RecID { get; set; }
        public string PartnerLink_Category { get; set; }
        public string PartnerLink_VRecID { get; set; }
        public string ProductLine { get; set; }
        public string ProductLine_Valid { get; set; }
        public string RecId { get; set; }
        public string RevenueType { get; set; }
        public string RevenueType_Valid { get; set; }
    }
}
