//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerContact
    {
        public string Address1Link_RecID { get; set; }
        public string Address1Link_Category { get; set; }
        public string Address1Link_VRecID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string DisplayName { get; set; }
        public string EmailLink_RecID { get; set; }
        public string EmailLink_Category { get; set; }
        public string EmailLink_VRecID { get; set; }
        public string FirstName { get; set; }
        public string Gender { get; set; }
        public string Gender_Valid { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string Phone1Link_RecID { get; set; }
        public string Phone1Link_Category { get; set; }
        public string Phone1Link_VRecID { get; set; }
        public string Phone2Link_RecID { get; set; }
        public string Phone2Link_Category { get; set; }
        public string Phone2Link_VRecID { get; set; }
        public string RecId { get; set; }
        public string Title { get; set; }
        public string Title_Valid { get; set; }
    }
}
