//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerCertification
    {
        public string CertificationLink_RecID { get; set; }
        public string CertificationLink_Category { get; set; }
        public string CertificationLink_VRecID { get; set; }
        public Nullable<System.DateTime> CertifiedDate { get; set; }
        public string ContactLink_RecID { get; set; }
        public string ContactLink_Category { get; set; }
        public string ContactLink_VRecID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string Name { get; set; }
        public string PartnerLink_RecID { get; set; }
        public string PartnerLink_Category { get; set; }
        public string PartnerLink_VRecID { get; set; }
        public string RecId { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
    }
}
