//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string PricingType { get; set; }
        public string PricingType_Valid { get; set; }
        public Nullable<decimal> PricingValue { get; set; }
        public Nullable<decimal> PricingValuePct { get; set; }
        public string PricingValuePct_Valid { get; set; }
        public string PricingText { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string TransactionCurrencyC_Valid { get; set; }
        public Nullable<decimal> mPricingValuePCV { get; set; }
        public Nullable<decimal> mPricingValueTCV { get; set; }
        public Nullable<bool> ShowPricingAmt { get; set; }
        public Nullable<bool> ShowPricingPct { get; set; }
        public Nullable<bool> ShowPricingValue { get; set; }
        public string Pricing1 { get; set; }
        public string Pricing_Valid { get; set; }
    }
}
