//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLine
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string OwnerType { get; set; }
        public string Owner { get; set; }
        public string OwnerTeam { get; set; }
        public string Description { get; set; }
        public string ParentLineLink_RecID { get; set; }
        public string ParentLineLink_Category { get; set; }
        public string ProductLine1 { get; set; }
        public string ProductLineManager { get; set; }
        public Nullable<byte> ProductLineScore { get; set; }
        public string ManagerLink_RecID { get; set; }
        public string ManagerLink_Category { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLine { get; set; }
        public string Pricing { get; set; }
        public string Pricing_Valid { get; set; }
        public Nullable<decimal> PricingValue { get; set; }
        public string PricingText { get; set; }
        public Nullable<bool> ShowPricingValue { get; set; }
        public string QuoteApprovalAuthority { get; set; }
        public string QuoteApprovalAuthori_RecID { get; set; }
        public string QuoteApprovalAuthori_Category { get; set; }
        public string QuoteApprovalAuthori_VRecID { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string TransactionCurrencyC_Valid { get; set; }
        public Nullable<decimal> mPricingValuePCV { get; set; }
        public Nullable<decimal> mPricingValueTCV { get; set; }
        public Nullable<decimal> PricingValuePct { get; set; }
        public string PricingValuePct_Valid { get; set; }
        public Nullable<bool> ShowPricingAmt { get; set; }
        public Nullable<bool> ShowPricingPct { get; set; }
        public string PricingLink_RecID { get; set; }
        public string PricingLink_Category { get; set; }
        public string PricingLink_VRecID { get; set; }
    }
}
