//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string ProfileType { get; set; }
        public string DisplayName { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ProfileID { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<decimal> ClosureRate { get; set; }
        public string ClosureRate_Valid { get; set; }
        public string ContactLoginLink_RecID { get; set; }
        public string ContactLoginLink_Category { get; set; }
        public string ContactLoginLink_VRecID { get; set; }
        public string DefaultCurrency { get; set; }
        public string DefaultCurrency_Valid { get; set; }
        public string Degree { get; set; }
        public string Degree_Valid { get; set; }
        public string Department { get; set; }
        public string Department_Valid { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<short> DirectReportCount { get; set; }
        public Nullable<int> Hierarchy_Left { get; set; }
        public Nullable<int> Hierarchy_Right { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmpSupervisorLink_RecID { get; set; }
        public string EmpSupervisorLink_Category { get; set; }
        public string EmpSupervisorLink_VRecID { get; set; }
        public string FirstName { get; set; }
        public string FRS { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public string GeographyName_Valid { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public Nullable<System.DateTime> HiredDate { get; set; }
        public Nullable<decimal> IVRPinCode { get; set; }
        public string LastName { get; set; }
        public string LoginID { get; set; }
        public string MiddleName { get; set; }
        public string NetworkUserName { get; set; }
        public Nullable<int> NextPeerHierarchyID { get; set; }
        public string NotificationLink_RecID { get; set; }
        public string NotificationLink_Category { get; set; }
        public string OLALink_RecID { get; set; }
        public string OLALink_Category { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string Phone1Link_RecID { get; set; }
        public string Phone1Link_Category { get; set; }
        public string Phone2Link_RecID { get; set; }
        public string Phone2Link_Category { get; set; }
        public string Phone3Link_RecID { get; set; }
        public string Phone3Link_Category { get; set; }
        public string Phone4Link_RecID { get; set; }
        public string Phone4Link_Category { get; set; }
        public string Prefix { get; set; }
        public string Prefix_Valid { get; set; }
        public string PrimaryAddressLink_RecID { get; set; }
        public string PrimaryAddressLink_Category { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryEmail_Valid { get; set; }
        public string PrimaryEmailLink_RecID { get; set; }
        public string PrimaryEmailLink_Category { get; set; }
        public string PrimaryWebLink_RecID { get; set; }
        public string PrimaryWebLink_Category { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionName_Valid { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public string Suffix { get; set; }
        public string Suffix_Valid { get; set; }
        public string Supervisor { get; set; }
        public string SupervisorLink_RecID { get; set; }
        public string SupervisorLink_Category { get; set; }
        public string Team { get; set; }
        public string Team_Valid { get; set; }
        public Nullable<System.DateTime> TerminatedDate { get; set; }
        public string Territory { get; set; }
        public string Territory_Valid { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string TerritoryName_Valid { get; set; }
        public string Title { get; set; }
        public string Title_Valid { get; set; }
        public Nullable<byte> YearsInSchool { get; set; }
        public Nullable<bool> No_Longer_Employed { get; set; }
    }
}
