//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public string AccountName { get; set; }
        public string ApprovalAuthorityID { get; set; }
        public Nullable<bool> br_BeforeSaveUpdates { get; set; }
        public Nullable<bool> br_EmptyOpptyLnkKey { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CURRENCYCODE { get; set; }
        public string CURRENCYCODE_Valid { get; set; }
        public string Description { get; set; }
        public string FinalState { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public string GeographyName_Valid { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public Nullable<bool> IgnoreStatusWhenGeneratingDoc { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public Nullable<decimal> mGrossAmountPCV { get; set; }
        public Nullable<decimal> mGrossAmountTCV { get; set; }
        public Nullable<decimal> mQuoteDiscountPCV { get; set; }
        public Nullable<decimal> mQuoteDiscountTCV { get; set; }
        public Nullable<decimal> mQuoteDiscountTempPCV { get; set; }
        public Nullable<decimal> mQuoteDiscountTempTCV { get; set; }
        public Nullable<decimal> mRevenuePCV { get; set; }
        public Nullable<decimal> mRevenueTCV { get; set; }
        public Nullable<decimal> mTaxAmountPCV { get; set; }
        public Nullable<decimal> mTaxAmountTCV { get; set; }
        public Nullable<decimal> mTaxAmountTempPCV { get; set; }
        public Nullable<decimal> mTaxAmountTempTCV { get; set; }
        public Nullable<decimal> mTotalAmountDuePCV { get; set; }
        public Nullable<decimal> mTotalAmountDueTCV { get; set; }
        public Nullable<decimal> mTotalListPricePCV { get; set; }
        public Nullable<decimal> mTotalListPriceTCV { get; set; }
        public string Name { get; set; }
        public string OpportunityLink_RecID { get; set; }
        public string OpportunityLink_Category { get; set; }
        public string OpportunityLink_VRecID { get; set; }
        public string OpportunityName { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string ProductLine { get; set; }
        public Nullable<decimal> QuoteDiscountPercentage { get; set; }
        public string QuoteNo { get; set; }
        public string QuoteNo_LnkKey { get; set; }
        public string RecId { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionName_Valid { get; set; }
        public string RejectingComments { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string TerritoryName_Valid { get; set; }
    }
}
