//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quota
    {
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CURRENCYCODE { get; set; }
        public string CURRENCYCODE_Valid { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeLink_RecID { get; set; }
        public string EmployeeLink_Category { get; set; }
        public string EmployeeLink_VRecID { get; set; }
        public Nullable<byte> FiscalYearLastMonth { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public string GeographyName_Valid { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public Nullable<decimal> m_Adjustment__PCV { get; set; }
        public Nullable<decimal> m_Adjustment__TCV { get; set; }
        public Nullable<decimal> m_Amount__PCV { get; set; }
        public Nullable<decimal> m_Amount__TCV { get; set; }
        public Nullable<decimal> m_InitialAmount__PCV { get; set; }
        public Nullable<decimal> m_InitialAmount__TCV { get; set; }
        public string Owner { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string ProductInterest { get; set; }
        public string ProductInterest_Valid { get; set; }
        public string QuotaMonth { get; set; }
        public string QuotaMonth_Valid { get; set; }
        public Nullable<byte> QuotaMonthIndex { get; set; }
        public string QuotaQuarter { get; set; }
        public string QuotaQuarter_Valid { get; set; }
        public string QuotaYear { get; set; }
        public string QuotaYear_Valid { get; set; }
        public Nullable<short> QuotaYearCalendar { get; set; }
        public string RecId { get; set; }
        public Nullable<bool> Recurring { get; set; }
        public Nullable<decimal> RecurringMonthlyPCV { get; set; }
        public Nullable<decimal> RecurringMonthlyTCV { get; set; }
        public Nullable<decimal> RecurringQuarterlyPCV { get; set; }
        public Nullable<decimal> RecurringQuarterlyTCV { get; set; }
        public Nullable<decimal> RecurringYearlyPCV { get; set; }
        public Nullable<decimal> RecurringYearlyTCV { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public string RegionName_Valid { get; set; }
        public string Territory { get; set; }
        public string Territory_Valid { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string TerritoryName_Valid { get; set; }
    }
}
