//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteApprovalConfiguration
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string OwnerType { get; set; }
        public string Owner { get; set; }
        public string OwnerTeam { get; set; }
        public Nullable<bool> IsApprovalRequired { get; set; }
        public Nullable<bool> Level1IsNotificationRequired { get; set; }
        public Nullable<int> Level1FollowupWaitTime { get; set; }
        public string Level1FollowupWaitTime_Valid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Level1IsActive { get; set; }
        public Nullable<decimal> Level1RevenueThreshold { get; set; }
        public Nullable<int> Level2FollowupWaitTime { get; set; }
        public Nullable<bool> Level2IsActive { get; set; }
        public Nullable<bool> Level2IsNotificationRequired { get; set; }
        public Nullable<bool> Level3IsNotificationRequired { get; set; }
        public Nullable<bool> Level3IsActive { get; set; }
        public Nullable<int> Level3FollowupWaitTime { get; set; }
        public Nullable<decimal> Level2RevenueThreshold { get; set; }
        public string Level2ApprovalAuthor_RecID { get; set; }
        public string Level2ApprovalAuthor_Category { get; set; }
        public string Level2ApprovalAuthor_VRecID { get; set; }
        public string Level3ApprovalAuthor_RecID { get; set; }
        public string Level3ApprovalAuthor_Category { get; set; }
        public string Level3ApprovalAuthor_VRecID { get; set; }
        public Nullable<bool> L1RevThresholdLEL2RevThreshold { get; set; }
        public Nullable<bool> L1DisThresholdLEL2DisThreshold { get; set; }
        public Nullable<byte> Level1DiscountPercentThreshold { get; set; }
        public Nullable<byte> Level2DiscountPercentThreshold { get; set; }
        public string ApprovalMode { get; set; }
        public string ApprovalMode_Valid { get; set; }
        public Nullable<bool> IsLevel1AAQuoteOwnerManager { get; set; }
        public Nullable<bool> IsLevel2AAQuoteOwner2LManager { get; set; }
        public string Level1ApprovalAuthor_RecID { get; set; }
        public string Level1ApprovalAuthor_Category { get; set; }
        public string Level1ApprovalAuthor_VRecID { get; set; }
        public Nullable<decimal> Level3RevenueThreshold { get; set; }
        public Nullable<byte> Level3DiscountPercentThreshold { get; set; }
        public Nullable<bool> L2DisThresholdLEL3DisThreshold { get; set; }
        public Nullable<bool> L2RevThresholdLEL3RevThreshold { get; set; }
        public Nullable<bool> L1DisThresholdLEL3DisThreshold { get; set; }
        public Nullable<bool> L1RevThresholdLEL3RevThreshold { get; set; }
    }
}
