//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringRevenueByTerritory
    {
        public string Territory { get; set; }
        public string RecId_Territory { get; set; }
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string AggregateWhichRows { get; set; }
        public Nullable<decimal> m_RecurrRevenueMonthly__TCV { get; set; }
        public Nullable<decimal> m_RecurrRevenueMonthly__PCV { get; set; }
        public Nullable<decimal> m_RecurrRevenueQuarterly__TCV { get; set; }
        public Nullable<decimal> m_RecurrRevenueQuarterly__PCV { get; set; }
        public Nullable<decimal> m_RecurrRevenueYearly__TCV { get; set; }
        public Nullable<decimal> m_RecurrRevenueYearly__PCV { get; set; }
    }
}
