//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMA
    {
        public string ContactLink_RecID { get; set; }
        public string ContactLink_Category { get; set; }
        public string ContactLink_VRecID { get; set; }
        public Nullable<decimal> CostToCustomer { get; set; }
        public Nullable<decimal> CostToCustomerPCV { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<bool> IsUnderWarranty { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string Notes { get; set; }
        public string OfferingLink_RecID { get; set; }
        public string OfferingLink_Category { get; set; }
        public string OfferingLink_VRecID { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string Reason { get; set; }
        public string Reason_Valid { get; set; }
        public string RecId { get; set; }
        public Nullable<int> RMANumber { get; set; }
        public string RMAStatus { get; set; }
        public string RMAStatus_Valid { get; set; }
        public string RMAType { get; set; }
        public string RMAType_Valid { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string TransactionCurrencyC_Valid { get; set; }
    }
}
