//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTerritory
    {
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string Description { get; set; }
        public Nullable<byte> GeographyCode { get; set; }
        public string GeographyName { get; set; }
        public Nullable<int> HierarchyID { get; set; }
        public Nullable<byte> HierarchyLevel { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string Name { get; set; }
        public Nullable<byte> NextHierarchyLevel { get; set; }
        public string Owner { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string ParentSalesTerritory_RecID { get; set; }
        public string ParentSalesTerritory_Category { get; set; }
        public string ParentSalesTerritory_VRecID { get; set; }
        public string RecId { get; set; }
        public Nullable<byte> RegionCode { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> Hierarchy_Left { get; set; }
        public Nullable<int> Hierarchy_Right { get; set; }
        public Nullable<byte> TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
    }
}
