//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesActivity
    {
        public Nullable<int> ActualDemo { get; set; }
        public Nullable<int> ActualDisCall { get; set; }
        public Nullable<int> ActualDisMeet { get; set; }
        public Nullable<int> ActualFace { get; set; }
        public Nullable<int> ActualInbound { get; set; }
        public Nullable<int> ActualLiveEvt { get; set; }
        public Nullable<int> ActualOutbound { get; set; }
        public Nullable<int> ActualPOC { get; set; }
        public Nullable<int> ActualProposal { get; set; }
        public Nullable<int> ActualPtnCall { get; set; }
        public Nullable<int> ActualPtnMeet { get; set; }
        public Nullable<int> ActualTradeShow { get; set; }
        public Nullable<int> ActualUserGrp { get; set; }
        public Nullable<int> ActualWebinar { get; set; }
        public string AggregateWhichRows { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string EmployeeFullName { get; set; }
        public string RecId_ProfileEmployee { get; set; }
        public string ForecastMonth { get; set; }
        public string ForecastQuarter { get; set; }
        public string ForecastWeek { get; set; }
        public string ForecastYear { get; set; }
        public string GeographyName { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public Nullable<int> PlannedDemo { get; set; }
        public Nullable<int> PlannedDisCall { get; set; }
        public Nullable<int> PlannedDisMeet { get; set; }
        public Nullable<int> PlannedFace { get; set; }
        public Nullable<int> PlannedInbound { get; set; }
        public Nullable<int> PlannedLiveEvt { get; set; }
        public Nullable<int> PlannedOutbound { get; set; }
        public Nullable<int> PlannedPOC { get; set; }
        public Nullable<int> PlannedProposal { get; set; }
        public Nullable<int> PlannedPtnCall { get; set; }
        public Nullable<int> PlannedPtnMeet { get; set; }
        public Nullable<int> PlannedTradeShow { get; set; }
        public Nullable<int> PlannedUserGrp { get; set; }
        public Nullable<int> PlannedWebinar { get; set; }
        public string RecId { get; set; }
        public string RegionName { get; set; }
        public string TerritoryName { get; set; }
    }
}
