//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerInformation
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string McM_Core_ServerType { get; set; }
        public string McM_NET_ServerType { get; set; }
        public string McM_TellerLinks_ServerType { get; set; }
        public string McM_MainImaging_ServerType { get; set; }
        public string McM_GPOD_ServerType { get; set; }
        public string McM_GIX_ServerType { get; set; }
        public string McM_RTI_ServerType { get; set; }
        public string McM_TRU_ServerType { get; set; }
        public string McM_Drive_ServerLocation { get; set; }
        public string McM_Drive_ServerLocation_Valid { get; set; }
        public string McM_Voice_ServerLocation { get; set; }
        public string McM_Voice_ServerLocation_Valid { get; set; }
        public string McM_CSP_ServerLocation { get; set; }
        public string McM_CSP_ServerLocation_Valid { get; set; }
        public string McM_Core_OC_Version { get; set; }
        public string McM_Core_Software { get; set; }
        public Nullable<System.DateTime> McM_Core_Install_Date { get; set; }
        public string McM_Core_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_Core_WarrantyEndDate { get; set; }
        public string McM_Core_Local_IP { get; set; }
        public string McM_Core_NAT_IP { get; set; }
        public string McM_Core_Purchased_From { get; set; }
        public string McM_Core_Purchased_From_Valid { get; set; }
        public string McM_Core_Support_Connection { get; set; }
        public string McM_Core_Support_Connection_Valid { get; set; }
        public string McM_NET_OC_Version { get; set; }
        public string McM_NET_Software { get; set; }
        public Nullable<System.DateTime> McM_NET_Install_Date { get; set; }
        public string McM_NET_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_NET_WarrantyEndDate { get; set; }
        public string McM_NET_Local_IP { get; set; }
        public string McM_NET_NAT_IP { get; set; }
        public string McM_NET_Purchased_From { get; set; }
        public string McM_NET_Purchased_From_Valid { get; set; }
        public string McM_NET_Support_Connection { get; set; }
        public string McM_NET_Support_Connection_Valid { get; set; }
        public string McM_Reptsys_ServerType { get; set; }
        public string McM_Reptsys_OC_Version { get; set; }
        public string McM_Reptsys_Software { get; set; }
        public Nullable<System.DateTime> McM_Reptsys_Install_Date { get; set; }
        public string McM_Reptsys_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_Reptsys_WarrantyEndDate { get; set; }
        public string McM_Reptsys_Local_IP { get; set; }
        public string McM_Reptsys_NAT_IP { get; set; }
        public string McM_Reptsys_Purchased_From { get; set; }
        public string McM_Reptsys_Purchased_From_Valid { get; set; }
        public string McM_Reptsys_Support_Connection { get; set; }
        public string McM_Reptsys_Support_Connection_Valid { get; set; }
        public string McM_TellerLinks_OC_Version { get; set; }
        public string McM_TellerLinks_Software { get; set; }
        public Nullable<System.DateTime> McM_TellerLinks_Install_Date { get; set; }
        public string McM_TellerLinks_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_TellerLinks_WarrantyEndDat { get; set; }
        public string McM_TellerLinks_Local_IP { get; set; }
        public string McM_TellerLinks_NAT_IP { get; set; }
        public string McM_TellerLinks_Purchased_From { get; set; }
        public string McM_TellerLinks_Purchased_From_Valid { get; set; }
        public string McM_TellerLinks_Support_Connec { get; set; }
        public string McM_TellerLinks_Support_Connec_Valid { get; set; }
        public string McM_MainImaging_OC_Version { get; set; }
        public string McM_MainImaging_Software { get; set; }
        public Nullable<System.DateTime> McM_MainImaging_Install_Date { get; set; }
        public string McM_MainImaging_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_MainImaging_WarantyEndDate { get; set; }
        public string McM_MainImaging_Local_IP { get; set; }
        public string McM_MainImaging_NAT_IP { get; set; }
        public string McM_MainImaging_Purchased_From { get; set; }
        public string McM_MainImaging_Purchased_From_Valid { get; set; }
        public string McM_MainImaging_Support_Connec { get; set; }
        public string McM_MainImaging_Support_Connec_Valid { get; set; }
        public string McM_GPOD_OC_Version { get; set; }
        public string McM_GPOD_Software { get; set; }
        public Nullable<System.DateTime> McM_GPOD_Install_Date { get; set; }
        public string McM_GPOD_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_GPOD_WarrantyEndDate { get; set; }
        public string McM_GPOD_Local_IP { get; set; }
        public string McM_GPOD_NAT_IP { get; set; }
        public string McM_GPOD_Purchased_From { get; set; }
        public string McM_GPOD_Purchased_From_Valid { get; set; }
        public string McM_GPOD_Support_Connection { get; set; }
        public string McM_GPOD_Support_Connection_Valid { get; set; }
        public string McM_GIX_OC_Version { get; set; }
        public string McM_GIX_Software { get; set; }
        public Nullable<System.DateTime> McM_GIX_Install_Date { get; set; }
        public string McM_GIX_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_GIX_WarrantyEndDate { get; set; }
        public string McM_GIX_Local_IP { get; set; }
        public string McM_GIX_NAT_IP { get; set; }
        public string McM_GIX_Purchased_From { get; set; }
        public string McM_GIX_Purchased_From_Valid { get; set; }
        public string McM_GIX_Support_Connection { get; set; }
        public string McM_GIX_Support_Connection_Valid { get; set; }
        public string McM_RTI_OC_Version { get; set; }
        public string McM_RTI_Software { get; set; }
        public Nullable<System.DateTime> McM_RTI_Install_Date { get; set; }
        public string McM_RTI_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_RTI_WarrantyEndDate { get; set; }
        public string McM_RTI_Local_IP { get; set; }
        public string MCM_RTI_NAT_IP { get; set; }
        public string McM_RTI_Purchased_From { get; set; }
        public string McM_RTI_Purchased_From_Valid { get; set; }
        public string McM_RTI_Support_Connection { get; set; }
        public string McM_RTI_Support_Connection_Valid { get; set; }
        public string McM_TRU_OC_Version { get; set; }
        public string MCM_TRU_Software { get; set; }
        public Nullable<System.DateTime> McM_TRU_Install_Date { get; set; }
        public string McM_TRU_ServiceTag { get; set; }
        public Nullable<System.DateTime> McM_TRU_WarrantyEndDate { get; set; }
        public string McM_TRU_Local_IP { get; set; }
        public string McM_TRU_NAT_IP { get; set; }
        public string McM_TRU_Purchased_From { get; set; }
        public string McM_TRU_Purchased_From_Valid { get; set; }
        public string McM_TRU_Support_Connection { get; set; }
        public string McM_TRU_Support_Connection_Valid { get; set; }
        public string McM_EFT_ServerLocation { get; set; }
        public string McM_EFT_ServerLocation_Valid { get; set; }
        public string McM_eft_1 { get; set; }
        public string McM_eft_1_Valid { get; set; }
        public string McM_Voice_Line_Type { get; set; }
        public string McM_Voice_Line_Type_Valid { get; set; }
        public string McM_Voice_SIP_IP { get; set; }
        public string McM_Voice_Line_Number { get; set; }
        public string McM_Voice_Contact { get; set; }
        public string WebAddress { get; set; }
        public string McM_Notes { get; set; }
        public Nullable<bool> McM_Core_Notes_Logical { get; set; }
        public Nullable<bool> McM_Core_Attachments_Logical { get; set; }
        public Nullable<bool> McM_Net_Notes_Logical { get; set; }
        public Nullable<bool> McM_Net_Attachments_Logical { get; set; }
        public Nullable<bool> McM_Reptsys_Notes_Logical { get; set; }
        public Nullable<bool> McM_Reptsys_Attach_Logical { get; set; }
        public Nullable<bool> McM_TellerLinks_Logical { get; set; }
        public Nullable<bool> McM_TellerLinks_Attach_Logical { get; set; }
        public Nullable<bool> McM_MainImaging_Notes_Logical { get; set; }
        public Nullable<bool> McM_MainImaging_Attach_Logical { get; set; }
        public Nullable<bool> McM_GPOD_Notes_Logical { get; set; }
        public Nullable<bool> McM_GPOD_Attach_Logical { get; set; }
        public Nullable<bool> McM_GIX_Notes_Logical { get; set; }
        public Nullable<bool> McM_GIX_Attach_Logical { get; set; }
        public Nullable<bool> McM_RTI_Notes_Logical { get; set; }
        public Nullable<bool> McM_RTI_Attach_Logical { get; set; }
        public Nullable<bool> McM_TRU_Notes_Logical { get; set; }
        public Nullable<bool> McM_TRU_Attach_Logical { get; set; }
        public Nullable<bool> McM_EFT_Notes_Logical { get; set; }
        public Nullable<bool> McM_EFT_Attach_Logical { get; set; }
        public Nullable<bool> McM_CSP_Notes_Logical { get; set; }
        public Nullable<bool> McM_CSP_Attachments_Logical { get; set; }
        public Nullable<bool> McM_Voice_Notes_Logical { get; set; }
        public Nullable<bool> McM_Voice_Attachment_Logical { get; set; }
        public Nullable<bool> McM_Drive_Notes_Logical { get; set; }
        public Nullable<bool> McM_Drive_Attachments_Logical { get; set; }
    }
}
