//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceContract
    {
        public string AccountLink_RecID { get; set; }
        public string AccountLink_Category { get; set; }
        public string AccountLink_VRecID { get; set; }
        public string AccountName { get; set; }
        public Nullable<bool> br_BeforeSaveUpdates { get; set; }
        public Nullable<decimal> CostToServiceEmail { get; set; }
        public Nullable<decimal> CostToServiceEmailPCV { get; set; }
        public Nullable<decimal> CostToServiceOnPremise { get; set; }
        public Nullable<decimal> CostToServiceOnPremisePCV { get; set; }
        public Nullable<decimal> CostToServicePhone { get; set; }
        public Nullable<decimal> CostToServicePhonePCV { get; set; }
        public Nullable<decimal> CostToServiceWeb { get; set; }
        public Nullable<decimal> CostToServiceWebPCV { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<short> ExpiryAlertDays { get; set; }
        public Nullable<byte> FiscalYearLastMonth { get; set; }
        public string ForecastQuarter { get; set; }
        public string ForecastYear { get; set; }
        public string GeographyName { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public Nullable<short> MaxAnyCount { get; set; }
        public Nullable<short> MaxEmailSupportCount { get; set; }
        public Nullable<short> MaxOnPremiseSupportCount { get; set; }
        public Nullable<short> MaxPhoneSupportCount { get; set; }
        public Nullable<short> MaxWebSupportCount { get; set; }
        public Nullable<bool> NoMaxLimits { get; set; }
        public Nullable<bool> PreventLogging { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public string ProductLine { get; set; }
        public string ProductLineLink_RecID { get; set; }
        public string ProductLineLink_Category { get; set; }
        public string ProductLineLink_VRecID { get; set; }
        public string RecId { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> ServiceContractNumber { get; set; }
        public string ServiceContractType { get; set; }
        public string ServiceContractType_Valid { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public string TerritoryName { get; set; }
        public string Title { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string TransactionCurrencyC_Valid { get; set; }
    }
}
