//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string Stage1 { get; set; }
        public Nullable<short> Probability { get; set; }
        public Nullable<short> SortField { get; set; }
        public Nullable<short> StageDuration { get; set; }
        public Nullable<short> StalledDealLimit { get; set; }
        public string Methodology { get; set; }
        public string Methodology_Valid { get; set; }
    }
}
