//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerritoryPricing
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string ParentLink_RecID { get; set; }
        public string ParentLink_Category { get; set; }
        public string ParentLink_VRecID { get; set; }
        public string Territory { get; set; }
        public string Territory_Valid { get; set; }
        public string TypeOfCurrency { get; set; }
        public string TypeOfCurrency_Valid { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public string Pricing { get; set; }
        public string Pricing_Valid { get; set; }
        public string Instruction { get; set; }
        public string CURRENCYCODE { get; set; }
        public Nullable<decimal> PricingValuePct { get; set; }
        public string PricingText { get; set; }
        public Nullable<bool> ShowFixedPrice { get; set; }
        public Nullable<bool> ShowListPrice { get; set; }
        public Nullable<bool> ShowPricingValue { get; set; }
        public Nullable<bool> ShowPricingAmt { get; set; }
        public Nullable<bool> ShowPricingPct { get; set; }
        public string PricingType { get; set; }
        public string PrimaryCurrencyCode { get; set; }
        public Nullable<decimal> m_MSRP__TCV { get; set; }
        public Nullable<decimal> m_MSRP__PCV { get; set; }
        public Nullable<decimal> m_Cost__TCV { get; set; }
        public Nullable<decimal> m_Cost__PCV { get; set; }
        public Nullable<decimal> m_ListPrice__TCV { get; set; }
        public Nullable<decimal> m_ListPrice__PCV { get; set; }
        public Nullable<decimal> m_PricingValue__TCV { get; set; }
        public Nullable<decimal> m_PricingValue__PCV { get; set; }
        public Nullable<decimal> m_FixedPrice__TCV { get; set; }
        public Nullable<decimal> m_FixedPrice__PCV { get; set; }
    }
}
