//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMKB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string Department { get; set; }
        public string Department_Valid { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Owner { get; set; }
        public string Owner_Valid { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerType { get; set; }
        public string Prefix { get; set; }
        public string Prefix_Valid { get; set; }
        public string ProfileID { get; set; }
        public string ProfileType { get; set; }
        public string Suffix { get; set; }
        public string Suffix_Valid { get; set; }
        public string Territory { get; set; }
        public string Territory_Valid { get; set; }
        public string Title { get; set; }
        public string Title_Valid { get; set; }
        public string VendorName { get; set; }
        public string VendorStatus { get; set; }
        public string VendorStatus_Valid { get; set; }
        public string Phone1Link_RecID { get; set; }
        public string Phone1Link_Category { get; set; }
        public string Phone1Link_VRecID { get; set; }
        public string Phone2Link_RecID { get; set; }
        public string Phone2Link_Category { get; set; }
        public string Phone2Link_VRecID { get; set; }
        public string Phone3Link_RecID { get; set; }
        public string Phone3Link_Category { get; set; }
        public string Phone3Link_VRecID { get; set; }
        public string Phone4Link_RecID { get; set; }
        public string Phone4Link_Category { get; set; }
        public string Phone4Link_VRecID { get; set; }
        public string PrimaryAddressLink_RecID { get; set; }
        public string PrimaryAddressLink_Category { get; set; }
        public string PrimaryAddressLink_VRecID { get; set; }
        public string PrimaryEmailLink_RecID { get; set; }
        public string PrimaryEmailLink_Category { get; set; }
        public string PrimaryEmailLink_VRecID { get; set; }
        public string PrimaryWebLink_RecID { get; set; }
        public string PrimaryWebLink_Category { get; set; }
        public string PrimaryWebLink_VRecID { get; set; }
    }
}
